image: node:8.9

variables:
  GITHUB_UPSTREAM: web_upstream
  GITHUB_URL: "https://$SECRET_GITHUB_DEPLOY_TOKEN@github.com/jhr007/rainbow-code-generator"

cache:
  paths:
    - dist
    - /usr/local/lib/node_modules

before_script:
  - git remote add -f $GITHUB_UPSTREAM $GITHUB_URL || /bin/true
  - git config user.email "GitLabCI"
  - git config user.name "GitLabCI"

push_upstream_github:
  script:
    - git push -f $GITHUB_UPSTREAM master

build_dist:
  script:
    - "[[ -f `which ember` ]] || npm install -g ember-cli"
    - npm install
    - ember build production

update_gh_pages:
  environment:
    name: github-pages
    url: "http://jhr007.github.io/rainbow-code-generator"
  script:
    - cd dist
    - git init
    - git remote add -f $GITHUB_UPSTREAM $GITHUB_URL || /bin/true
    - git checkout --orphan gh-pages
    - git add -f .
    - git commit -m'Github pages'
    - git push $GITHUB_UPSTREAM gh-pages
